name: spdel 
channels:
  - eaton-lab
  - etetoolkit
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - ete3 
  - toytree
  - pip:
    - git+https://github.com/shh-dlce/python-nexus.git#python-nexus[complete]
    - git+https://github.com/jolobito/SPdel.git#spdel

