name: spdel
channels:
  - etetoolkit
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ete3 
  - toytree
  - python-kaleido
  - pip:
    - git+https://github.com/jolobito/SPdel.git#spdel


