name: spdel
channels:
  - eaton-lab
  - etetoolkit
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - ete3 
  - toytree
  - ipykernel
  - jupyter
  - pip:
    - git+https://github.com/jolobito/SPdel.git#spdel


