name: spdel 
channels:
  - eaton-lab
  - etetoolkit
  - bioconda
  - defaults
dependencies:
  - python=3
  - pip
  - ete3 
  - toytree
  - pip:
    - git+https://github.com/shh-dlce/python-nexus.git#python-nexus[complete]
    - git+https://github.com/Ulises-Rosas/SPdel.git#spdel

